#!/bin/bash

if [ $# -lt 1 ]; then
echo "Usage: ./prepare_data (depth of directory)"
echo "Depth of directory : Number of files"
echo "1 : 100"
echo "2 : 10000"
echo "3 : 1000000"
echo "4 : 100000000"
exit;
fi

if [ $1 -gt 4 ]; then
echo "Max depth is: 4 "
exit;
fi

java -cp /home/condor/alluxio/core/client/runtime/target/alluxio-core-client-runtime-1.6.1-jar-with-dependencies.jar:. Write $1

