#!/bin/bash
g++ -std=c++11 data_generator.cc -I/home/condor/install/liballuxio/include -I/usr/software/java/jdk1.8.0_121/include/ -I/usr/software/java/jdk1.8.0_121/include/linux -L/home/condor/install/liballuxio/lib -lalluxio -o data_generator




